/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations.index'
import { Route as ConversationsIdRouteImport } from './routes/conversations.$id'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiEdgeSpeakRouteImport } from './routes/api/edge-speak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEdgeSpeakRoute = ApiEdgeSpeakRouteImport.update({
  id: '/api/edge-speak',
  path: '/api/edge-speak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/edge-speak': typeof ApiEdgeSpeakRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/edge-speak': typeof ApiEdgeSpeakRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations': typeof ConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/edge-speak': typeof ApiEdgeSpeakRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/': typeof ConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/edge-speak'
    | '/api/speak'
    | '/api/transcribe'
    | '/conversations/$id'
    | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/edge-speak'
    | '/api/speak'
    | '/api/transcribe'
    | '/conversations/$id'
    | '/conversations'
  id:
    | '__root__'
    | '/'
    | '/api/edge-speak'
    | '/api/speak'
    | '/api/transcribe'
    | '/conversations/$id'
    | '/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEdgeSpeakRoute: typeof ApiEdgeSpeakRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edge-speak': {
      id: '/api/edge-speak'
      path: '/api/edge-speak'
      fullPath: '/api/edge-speak'
      preLoaderRoute: typeof ApiEdgeSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEdgeSpeakRoute: ApiEdgeSpeakRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
